#!/bin/sh

# ====================================
# Install aur packages
# ====================================

if pacman -Qs yay > /dev/null ; then
    echo "Yay is already installed, moving on..."
else
    rm -rf yay
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si --noconfirm
fi


yay -S polybar \
	nerd-fonts-cascadia-code \
	nerd-fonts-fira-code \
	pulseaudio-ctl \
	spotify \
	direnv \
	zoom \
	slack-desktop \
	visual-studio-code-bin \
	tela-icon-theme \
	google-chrome \
	postman \
	--needed --removemake --nocleanmenu --nodiffmenu --noeditmenu --noconfirm


