#!/bin/sh

# ====================================
# Install packages
# ====================================

# sh $HOME/.config/yadm/pacman-packages

# sh $HOME/.config/yadm/aur-packages

#if command -v nvm > /dev/null ; then
#    echo "nvm is already installed, moving on..."
#else
#    wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
#fi

#if pacman -Qs docker > /dev/null ; then
#    echo "Docker is already installed, moving on..."
#else
#    sudo pacman -S docker --noconfirm --needed
#    sudo groupadd docker
#    sudo usermod -aG docker $USER
#    sudo systemctl enable docker
#fi



# ====================================
# Download and set background
# ====================================

#mkdir ~/Documents &> /dev/null
#mkdir ~/Documents/Wallpapers &> /dev/null
#curl https://i.imgur.com/XCaXGFB.png > ~/Documents/Wallpapers/gruvbox.png

# ====================================
# Polybar font
# ====================================

#mkdir ~/.local &> /dev/null
#mkdir ~/.local/share &> /dev/null
#mkdir ~/.local/share/fonts &> /dev/null
#curl https://raw.githubusercontent.com/adi1090x/polybar-themes/master/polybar-8/fonts/icomoon-feather.ttf > icomoon-feather.ttf
#mv icomoon-feather.ttf ~/.local/share/fonts/
#fc-cache -vf ~/.local/share/fonts/

# ====================================
# Powerline arrow fix
# ====================================

wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
mv PowerlineSymbols.otf ~/.local/share/fonts/
fc-cache -vf ~/.local/share/fonts/
mkdir ~/.config/fontconfig
mkdir ~/.config/fontconfig/conf.d
mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/




# Make pacman display colored output
# sudo sed -i 's/#Color/Color/g' /etc/pacman.conf

# =========================================
# Install oh my zsh and zsh-autosuggestions
# =========================================

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended --keep-zshrc"
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k


echo "=============="
echo "==== DONE ===="
echo "=============="
echo "$ chsh -s /bin/zsh"
echo "$ startx"
echo "$ feh --bg-fill ~/Documents/Wallpapers/wallpaper.png"

# Change to zsh
zsh
