#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config border_radius         12
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a zoom state=floating desktop=^5
bspc rule -a Slack desktop=^3
bspc rule -a discord desktop=^3

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
feh --bg-fill ~/Pictures/Wallpapers/rick_morty.jpg &
# Reload .Xresources
xrdb -load ~/.Xresources &
# Launch polybar
~/.config/polybar/launch.sh &
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
sudo betterlockscreen -u ~/Documents/Wallpapers/gruvbox.png
# ------- Autostart apps ------
# Picom
picom --xrender-sync-fence &
# Dunst
dunst &
# Clipman
xfce4-clipman &
# Bluethoot
blueman-applet &
# Nm-applet
nm-applet &
pasystray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# ------- Mouse/Touchpad fixes ------
# Start libinput gestures
libinput-gestures-setup start
# Xinput configs (touchpad)
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0
# ------- Keyboard fixes ------
# Remap Caps-lock key to Escape, for using VIM
setxkbmap -option caps:escape
# Make US and DK keyboard layout togglable with Shift+Alt
setxkbmap -layout us,es -option grp:alt_shift_toggle


